// export { default as Login } from "./LoginForm/Login";
export { default as NavBar } from "./NavBar/NavBar";
export { default as Cart } from "./Cart/Cart";
export { default as Dashboard } from "./Dashboard/Dashboard";
export { default as ProductDetail } from "./Product/ProductDetail";
export { default as Checkout } from "./CheckoutForm/Checkout";
export { default as Loader } from "./Loader/Loader";
export { default as Order } from "./Order/Order";
export { default as OrderDetail } from "./Order/OrderDetail/OrderDetail";
export { default as Footer } from "./Footer/Footer";
export { default as NotFound } from "./NotFound/NotFound";
